replicaCount: 3

image:
  repository: acripreverser.azurecr.io/ip-reverser-app
  pullPolicy: Always
  tag: "10"

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: ip-reverser.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ip-reverser-tls
      hosts:
        - ip-reverser.yourdomain.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "supersecurepassword"
    database: "ipreverser"
  primary:
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Environment variables
env:
  - name: DB_HOST
    value: "ip-reverser-postgresql"
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "ipreverser"
  - name: DB_USER
    value: "postgres"
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ip-reverser-postgresql
        key: postgres-password

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001

# Security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

# Liveness and readiness probes
livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Service monitor for Prometheus
serviceMonitor:
  enabled: true
  labels:
    app: ip-reverser
  interval: 30s
  scrapeTimeout: 10s