config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: [HTTP/1.1, HTTP/2.0]
        valid_status_codes: [200]
        method: GET
        preferred_ip_protocol: ip4

serviceMonitor:
  enabled: true
  defaults:
    labels:
      app: blackbox-exporter
    interval: 30s
    scrapeTimeout: 30s
  targets:
    - name: ip-reverser-health
      url: http://ip-reverser.ip-reverser.svc.cluster.local/health
      module: http_2xx